/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControllerMusica;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Gustavo
 */
public class CadastrarMusica extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarMusica
     */
    public CadastrarMusica() {
        initComponents();
    }

    public JTextField getTxt_artista_musica() {
        return Txt_artista_musica;
    }

    public void setTxt_artista_musica(JTextField Txt_artista_musica) {
        this.Txt_artista_musica = Txt_artista_musica;
    }

    public JTextField getTxt_genero_musica() {
        return Txt_genero_musica;
    }

    public void setTxt_genero_musica(JTextField Txt_genero_musica) {
        this.Txt_genero_musica = Txt_genero_musica;
    }

    public JTextField getTxt_lancamento_musica() {
        return Txt_lancamento_musica;
    }

    public void setTxt_lancamento_musica(JTextField Txt_lancamento_musica) {
        this.Txt_lancamento_musica = Txt_lancamento_musica;
    }

    public JTextField getTxt_titulo_musica() {
        return Txt_titulo_musica;
    }

    public void setTxt_titulo_musica(JTextField Txt_titulo_musica) {
        this.Txt_titulo_musica = Txt_titulo_musica;
    }

    public JButton getBt_confirmar_cadastro_musica() {
        return bt_confirmar_cadastro_musica;
    }

    public void setBt_confirmar_cadastro_musica(JButton bt_confirmar_cadastro_musica) {
        this.bt_confirmar_cadastro_musica = bt_confirmar_cadastro_musica;
    }

    public JButton getBt_voltar_tela_admin() {
        return bt_voltar_tela_admin;
    }

    public void setBt_voltar_tela_admin(JButton bt_voltar_tela_admin) {
        this.bt_voltar_tela_admin = bt_voltar_tela_admin;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Txt_titulo_musica = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Txt_genero_musica = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Txt_lancamento_musica = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Txt_artista_musica = new javax.swing.JTextField();
        bt_confirmar_cadastro_musica = new javax.swing.JButton();
        bt_voltar_tela_admin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastrar Musica");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Titulo:");

        Txt_titulo_musica.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Genero:");

        Txt_genero_musica.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Lançamento(ano-mes-dia):");

        Txt_lancamento_musica.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Artista:");

        Txt_artista_musica.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        bt_confirmar_cadastro_musica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_confirmar_cadastro_musica.setText("Confirmar");
        bt_confirmar_cadastro_musica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_confirmar_cadastro_musicaActionPerformed(evt);
            }
        });

        bt_voltar_tela_admin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_voltar_tela_admin.setText("Voltar");
        bt_voltar_tela_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltar_tela_adminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(bt_voltar_tela_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                        .addComponent(bt_confirmar_cadastro_musica, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(Txt_genero_musica)
                            .addComponent(Txt_titulo_musica)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Txt_lancamento_musica)
                            .addComponent(Txt_artista_musica))))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Txt_titulo_musica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Txt_genero_musica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Txt_lancamento_musica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Txt_artista_musica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_confirmar_cadastro_musica, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(bt_voltar_tela_admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_voltar_tela_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltar_tela_adminActionPerformed
        // TODO add your handling code here:
        // Cria e exibe a tela do Admin
        Adm adm = new Adm();
        adm.setVisible(true);
        
        this.dispose(); // Fecha a janela do cadastro de musica
    }//GEN-LAST:event_bt_voltar_tela_adminActionPerformed

    private void bt_confirmar_cadastro_musicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_confirmar_cadastro_musicaActionPerformed
        // TODO add your handling code here:
        ControllerMusica controller = new ControllerMusica(this);
        controller.cadastrarMusica();
        
    }//GEN-LAST:event_bt_confirmar_cadastro_musicaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CadastrarMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CadastrarMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CadastrarMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CadastrarMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CadastrarMusica().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Txt_artista_musica;
    private javax.swing.JTextField Txt_genero_musica;
    private javax.swing.JTextField Txt_lancamento_musica;
    private javax.swing.JTextField Txt_titulo_musica;
    private javax.swing.JButton bt_confirmar_cadastro_musica;
    private javax.swing.JButton bt_voltar_tela_admin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
